---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: containerd-registrar-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: containerd-registrar-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: containerd-registrar
    app.kubernetes.io/version: latest
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "update", "watch"]
- apiGroups: [""]
  resources: ["pods", "pods/status"]
  verbs: ["get", "list", "watch"]
