---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: containerd-registrar-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: containerd-registrar-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: containerd-registrar
    app.kubernetes.io/version: latest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: containerd-registrar-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: containerd-registrar-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: containerd-registrar
        app.kubernetes.io/version: latest
    spec:
      containers:
      - name: controller
        image: xinau/containerd-registrar:latest
        imagePullPolicy: Always
        args:
          - "controller"
          - "--agent.labels=app.kubernetes.io/name=containerd-registrar-controller"
          - "--agent.namespace=kube-system"
          - "--agent.nodetaint=node.containerd-registrar.io/agent-not-ready"
        resources:
          requests:
            memory: 128Mi
            cpu: 100m
          limits:
            memory: 128Mi
      serviceAccountName: containerd-registrar-controller
      tolerations:
        - key: node.containerd-registrar.io/agent-not-ready
          effect: NoSchedule
          operator: Exists
