---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: containerd-registrar-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: containerd-registrar-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: containerd-registrar
    app.kubernetes.io/version: latest
