---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: containerd-registrar-controller
  namespace: kube-system
  labels:
    app.kubernetes.io/name: containerd-registrar-controller
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: containerd-registrar
    app.kubernetes.io/version: latest
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: containerd-registrar-controller
subjects:
- kind: ServiceAccount
  name: containerd-registrar-controller
  namespace: kube-system
